### ISSUE TITLE
Not all data is read out // NRGkick Connect // DiniTech GmbH

### ISSUE THREAD

**Issue by ghost** [lbbrhzn/ocpp#1004]
Hello, 

I connected the NRGkick (new version) today. Everything works so far.
Unfortunately, very little data is displayed (read out). 
It would be nice if I could read all the data from the NRGkick and it would also be possible to make adjustments.
What data is needed to carry out an expansion? I can request the interface description.

Can anyone support. Thanks

NRGkick Connect / DiniTech GmbH
Firmware: SM:3.1.0.67/MC:3.1.2.1

<img width="269" alt="2023-12-11 14_52_58-Einstellungen – Home Assistant und 8 weitere Seiten - Geschäftlich – Microsoft​ " src="https://github.com/lbbrhzn/ocpp/assets/151848159/0465fbba-42ca-428f-9365-6f103264db86">
<img width="234" alt="2023-12-11 14_53_40-Einstellungen – Home Assistant und 8 weitere Seiten - Geschäftlich – Microsoft​ " src="https://github.com/lbbrhzn/ocpp/assets/151848159/865bbdc2-7e3e-48ea-b882-4aadb998b530">
<img width="254" alt="2023-12-11 14_52_33-" src="https://github.com/lbbrhzn/ocpp/assets/151848159/d7ad15d2-668e-4027-98b3-ac5e375e1cd1">
<img width="228" alt="2023-12-11 14_52_48-Einstellungen – Home Assistant und 8 weitere Seiten - Geschäftlich – Microsoft​ " src="https://github.com/lbbrhzn/ocpp/assets/151848159/660fc8ec-95f0-4bbe-8082-d86d0661666d">

<img width="349" alt="image" src="https://github.com/lbbrhzn/ocpp/assets/151848159/9491914e-018f-4bd6-88ec-f0cfce104e9d">

**Comment by TSK7M** [comment]
NRGKick Integration --> But only accessible via WiFi LAN.
It would be great if the functions were also available via OCPP. This means that data can also be recorded mobile via the GSM/UMTS connection (NRGKick).

NRGKick Integration
https://github.com/dupondje/nrgkick-ha

NRGKick Proto
https://github.com/dupondje/nrgkick-proto



<img width="364" alt="image" src="https://github.com/lbbrhzn/ocpp/assets/151848159/db853c27-c7a3-427d-a123-fa34400530c6">

<img width="365" alt="image" src="https://github.com/lbbrhzn/ocpp/assets/151848159/58cebfdc-9b41-4925-9621-45a6a42a3c60">

**Comment by TSK7M** [comment]
<img width="791" alt="image" src="https://github.com/lbbrhzn/ocpp/assets/151848159/d961b457-0fa6-4aa8-b728-a08731197ddc">

**Comment by TSK7M** [comment]
**python**

About the Custom API is possible, not currently supported devices or Involve manufacturers.
To do this they have to Device data requested and via web server to the NRGkick be communicated.
The Python script Custom_API_Webserver. py is used by DiniTech available placed.

`from socket import * # Import default python socket library
import json # Import default python json library

# Requirements / Steps:
# Adapt ‚deviceValues‘ and ‚deviceInfo‘ with your values
# Values of ‚deviceValues‘ shall be updated with a maximum interval of 7s
# Configuration ‚webserverHost‘ and ‚webserverPort‘ must be set to correct values
# Entered ‚webserverHost‘ and ‚webserverPort‘ then need to be entered in configuration in the app under custom api
# Skript must be run continuously to provide correct data for nrgkick
deviceValues = {
“device_values“: {
“inverters“: {
“0“: {
“inv_power_ac_w“: 2225, # Set current ac inverter power in W
“pv_energy_day_wh“: 8750, # Set day energy generation of the inverter in Wh
“pv_energy_total_wh“: 346890, # Set total energy generation of the inverter in Wh
“battery_connected“: True, # Set if configured battery is connected to this inverter
}
},
“energy_meters“: {
“0“: {“grid_power_w“: -542} # Set current total grid power in W
},
“batteries“: {
“0“: {
“bat_power_w“: -749, # Set current battery power in W
“soc“: 78.2, # Set current battery soc in %
“mode“: 0, # Set current battery mode
}
},
“smart_loads“: {
“0“: {
“sl_power_w“: 1241, # Set current smart load power in W
“temp“: 46.8, # Set current smart load temperature in °C
“mode“: 1, # Set current smart load mode
}
},
“load_power_w“: 1683, # Set current house load in W
}
}
deviceInfo = {
“device_info“: {
“inverters“: {
“0“: {
“name“: “Testinverter“, # Set name of inverter
“model“: “Testmodel“, # Set model of inverter
“serial“: “0123456789“, # Set serial number of inverter
“max_dc_w“: 5500, # Set maximum / connected dc power in W
“max_ac_w“: 5000, # Set maximum ac power in W
}
},
“energy_meters“: {
“0“: {
“name“: “Testmeter“, # Set name of smart meter
“model“: “Testmodel“, # Set model of smart meter
“serial“: “0123456789“, # Set serial number of smart meter
2. Skript zum Kopieren
“location“: 1, # Set meter location
}
},
“batteries“: {
“0“: {
“name“: “Testbatterie“, # Set name of battery
“model“: “Testmodel“, # Set model of battery
“serial“: “0123456789“, # Set serial of battery
“capacity_wh“: 4700, # Set capacity of battery in Wh
}
},
“smart_loads“: {
“0“: {
“name“: “Testsmartload“, # Set name of smart load
“model“: “Testmodel“, # Set model of smart load
“serial“: “0123456789“, # Ser serial of smart load
}
},
}
}
webserverHost = “localhost“ # Server ip address
webserverPort = 1000 # Server port
hs = socket(AF_INET, SOCK_STREAM) # Create socket for communication
hs.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1) # Set option to allow reusing Port
hs.bind((webserverHost, webserverPort)) # Bind created socket to configured host and port
hs.listen(1) # Listen do connection on created socket
# Print information log about webserver status
print(“Webserver is running on host “ + webserverHost + “ with port “ + str(webserverPort))
while True: # Loop for handling of inncomming connections
cc, ca = hs.accept() # Accept incomming connections
rawRequest = cc.recv(1024).decode( “utf-8“) # Receive incomming data and decode raw bytes into string
reqHeaders = rawRequest.split(“\r\n“) # Split individual headers
idxHeader = reqHeaders[0].split(“ “) # Split index header
reqType = idxHeader[0] # Parse request type
reqPath = idxHeader[1] # Parse request path
# Print information log about incomming connection
print(“Received “ + reqType + “ request with path “ + reqPath + “ from client “ + ca[0] + “ with port “ + str(ca[1]))
if reqType == “GET“: # Handle only get requests
if reqPath == “/api/v1/values.json“: # Respond to device values request
statusCode = “200 OK“ # Set standardised response code
headerType = “application/json“ # Set standardised response type
respData = json.dumps(deviceValues) # Set default response text
elif reqPath == “/api/v1/info.json“: # Respond to device info request
statusCode = “200 OK“ # Set standardised response code
headerType = “application/json“ # Set standardised response type
respData = json.dumps(deviceInfo) # Set default response text
else: # Respond to not defined request paths with error code 404
statusCode = “404 Not Found“ # Set standardised response code
headerType = “application/json“ # Set standardised response type
respData = json.dumps({“error“: „not found“}) # Set default response text
else: # Respond to other request types than get with error code 500
statusCode = “500 Internal Server Error“ # Set standardised response code
headerType = “application/json“ # Set standardised response type
respData = json.dumps(
{“error“: “internal server error“} # Set default response text
)
response = ( # Set data for transmit
“HTTP/1.1 “
+ statusCode
+ “\r\n“
+ “Content-Type: “ # Set http index header
+ headerType
+ “\r\n“
+ “Content-Length: “ # Set content type header
+ str(len(respData))
+ “\r\n“
+ “Connection: close\r\n“ # Set content length header
+ “\r\n“ # Set connection close header do disable connection keep alive
+ respData # Set empty line to set end of header segment
)
cc.sendall(response.encode(“utf-8“)) # Encode response string to bytes and send response
cc.close() # Close open connection after send is complete
hs.close()`

**Comment by TSK7M** [comment]
Custom API - PDF

[20231005_PV-Anleitung-Custom-API_03_web.pdf](https://github.com/lbbrhzn/ocpp/files/13661080/20231005_PV-Anleitung-Custom-API_03_web.pdf)

**Comment by maivorbim** [comment]
I am also interested in helping develop ocpp protocol or webapi. Let me know if I can help

**Comment by TSK7M** [comment]
I am also interested

**Comment by KETRF** [comment]
I wanted to share an alternative software that might be more suitable for this application and is compatible with the current software version of the NRGkick. You can check out the OCPP.Core project, which is an OCPP (Open ChargePoint Protocol) server written in .NET 8. It includes a management Web-UI for administration of charge points and charge tokens (RFID-Token).

You can find more information and the software at the following link: [OCPP.Core GitHub Repository](https://github.com/dallmann-consulting/OCPP.Core?tab=readme-ov-file#status).
