### ISSUE TITLE
Another working device: maXpeedingrods ev level 2 charger

### ISSUE THREAD

**Issue by scotthernandez** [lbbrhzn/ocpp#1022]
Hi,

I just wanted to provide a confirmation that this charger works; I'm using it with the home assistant integration to dynamically change charging power using my excess solar generation.

Here is an amazon product link (and extras):
https://www.amazon.com/gp/product/B0C7VV7K63/

These also seem to be the same product:
https://www.amazon.com/maXpeedingrods-Charger-Electric-Charging-Adjustable/dp/B0BZ7Y54GY
https://www.amazon.com/maXpeedingrods-Charger-Electric-Charging-Adjustable/dp/B0BBPZLW8B
https://www.amazon.com/maXpeedingrods-Charger-forTesla-Electric-Charging/dp/B0CJHWPZZ5

Thanks for your work on the project, btw.

**Comment by lbbrhzn** [comment]
Thanks, @scotthernandez ! I updated the documentation.
