### ISSUE TITLE
What to do when I temporarily turn off the opcc server and then turn it back on? I want the ev charger to automatically connect to the opcc server without us having to go into the terra config app to configure a new connection.

### ISSUE THREAD

**Issue by not1951aw** [lbbrhzn/ocpp#1092]
What to do when I temporarily turn off the opcc server and then turn it back on? I want the ev charger to automatically connect to the opcc server without us having to go into the terra config app to configure a new connection.

**Comment by lbbrhzn** [comment]
When you temporarily turn of the OCPP server the charger is disconnected.  The charger should attempt to reconnect automatically.  There is nothing the server side can do: the connection is initiated by the client.
