### ISSUE TITLE
Setting up measurands in 0.5.1 

### ISSUE THREAD

**Issue by stefan73** [lbbrhzn/ocpp#1098]
I am using an IOCharger / Entratek Wallbox with version 0.5.1. The OCPP integration works. I can start/stop the charging process and change the current. 

Question: How to set-up the measurands in the OCPP integration?
The read the docs link lists a dialog for that https://home-assistant-ocpp.readthedocs.io/en/latest/installation.html#measurands
I never get to this dialog. Neither when adding the integration nor within the options later on. 

The problem: Some of the values (specifically current and voltage) reported by the charger are updated every 15 min / 900s only. I can log into the charger's WebUI and add e.g. Current.Import to the list of Measurands (MeterValuesSampledData). This works for the moment. Every time the OCPP integration in HA gets restarted, the integration seems to update the Measurands in the charger to a minimum default setting.

[ocpp.txt](https://github.com/lbbrhzn/ocpp/files/14453801/ocpp.txt)

**Comment by lbbrhzn** [comment]
The dialog has been removed since v 0.5.x. The integration now autodetects the supported measurands.
