### ISSUE TITLE
Status intermittent between not available and available

### ISSUE THREAD

**Issue by StefanoGiu** [lbbrhzn/ocpp#1126]
**Describe the bug**
Status intermittent between not available and available

**To Reproduce**
check the status of the integration

**Expected behavior**
Status should be stable and not become available every minute

**Desktop (please complete the following information):**
 - Version [e.g. 22] 0.5.2

**Comment by StefanoGiu** [comment]
Any update? This custom component became unusable...

**Comment by StefanoGiu** [comment]
Still happening.... any willingness or plan to fix this?

**Comment by Aure51800** [comment]
Hi there, same here.
I can't find how to reproduce it. 
I know the last working version was 0.5.1
Entities become unavailable every 5s
What should I give you to debug ?

**Comment by Aure51800** [comment]
Hi, after some testes, it happens every 40s, with errors:
Enregistreur: custom_components.ocpp
Source: custom_components/ocpp/api.py:223
intégration: Open Charge Point Protocol (OCPP) ([documentation](https://github.com/lbbrhzn/ocpp/blob/main/README.md), [problèmes](https://github.com/lbbrhzn/ocpp/issues))
S'est produit pour la première fois: 21:46:38 (12 occurrences)
Dernier enregistrement: 21:56:33

Skipping websocket subprotocol validation


And 

Enregistreur: custom_components.ocpp
Source: custom_components/ocpp/api.py:1020
intégration: Open Charge Point Protocol (OCPP) ([documentation](https://github.com/lbbrhzn/ocpp/blob/main/README.md), [problèmes](https://github.com/lbbrhzn/ocpp/issues))
S'est produit pour la première fois: 21:46:54 (10 occurrences)
Dernier enregistrement: 21:56:03

Unexpected exception in connection to 'TACW2244421S5041': 'list index out of range'
Traceback (most recent call last):
  File "/config/custom_components/ocpp/api.py", line 1020, in run
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/ocpp/api.py", line 489, in post_connect
    resp = await self.get_configuration(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ocpp/api.py", line 889, in get_configuration
    value = resp.configuration_key[0][om.value.value]
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Aure51800** [comment]
And some more debugging logs

2024-05-20 22:49:45.180 INFO (MainThread) [ocpp] TACW2244421S5041: send [2,"03ab8853-0018-4024-bb5e-eec544199c7d","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Voltage"}]
2024-05-20 22:49:45.679 INFO (MainThread) [ocpp] TACW2244421S5041: receive message [3, "03ab8853-0018-4024-bb5e-eec544199c7d", {"status": "NotSupported"}]
2024-05-20 22:49:45.679 DEBUG (MainThread) [custom_components.ocpp] 'TACW2244421S5041' measurands not configurable by OCPP
2024-05-20 22:49:45.680 INFO (MainThread) [ocpp] TACW2244421S5041: send [2,"417df093-3b29-4365-b06e-e859668851ba","GetConfiguration",{"key":["MeterValuesSampledData"]}]
2024-05-20 22:49:46.179 INFO (MainThread) [ocpp] TACW2244421S5041: receive message [3, "417df093-3b29-4365-b06e-e859668851ba", {"configurationKey": [], "unknownKey": ["MeterValuesSampledData"]}]
2024-05-20 22:49:46.179 ERROR (MainThread) [custom_components.ocpp] Unexpected exception in connection to 'TACW2244421S5041': 'list index out of range'

**Comment by Aure51800** [comment]
No news ?

**Comment by ppnacho** [comment]
Same here. Some workaround? thanks

**Comment by SAUhrich** [comment]
No new information here, just reporting the same issue. I have had a MaxpeedingRods charger connected without problems for about 7 months up through using 0,5,1, After upgrading to 0.5.2 it connects to the charger correctly for about 30 seconds, and then disconnects for about 60 seconds, Interestingly, when it is connected, I can read and control the charger,

I have tried each successive version after 0,5,1 with the same results, and cannot now go back ti 0,5,1, I tried manually copying the files from 0.5.1 to the ocpp folder, but, same results. I will note that when I updated ocpp, it happened at the same time that an HA core update occurred, so it's possible that some combination of the HA update caused the issues?

I have deleted my setup entities (central and charger) to stop getting the hundreds of error messages per day, but left the integration loaded to watch for a new update to ocpp. It wouldn't be right to complain about someone's work that they graciously shared for free, I'm just hopeful that a future update will resolve the issue. Like others, I have setup automations that control my charger (I'm 100% solar) and became dependent on the integration,

**Comment by Aure51800** [comment]
Hi guys,
Good news, I have ABB TACW 22 with this problem, as there were no news here, I tried to update my wallbox, delivered with software 1.5.2 to 1.8.21 (3 major update to do). Now there is no more problem with loosing connection.
You can proceed do the upgrade with Charge Sync APP or TerraConfig ( both Need to register but free).
Please don't forget to screenshot every configuration pages, as I lost my config (modbus etc) from 1.6.6 to 1.7.1

enjoy!

**Comment by StefanoGiu** [comment]
I upgraded to 1.8.21 but the problem persists. I have also checked that the wallbox is not accessible via Charger Sync App Legacy or TerraConfig in WiFi, but only in bluetooth, even if the wifi is configured properly and the router is nearby. The wallbox is still using wifi somehow because the OCPP server is updated (even if intermittently). Can you please suggest?

**Comment by Aure51800** [comment]
Hi,
This is normal that you can only access your wall box on chargersync or terraconfig with Bluetooth.
When you choose your customized server, please stay in http://homeassistantadress:port
Give the same port on occp and disable configuration check on occp

**Comment by StefanoGiu** [comment]
Actually my OCPP server is accessible from the url ws://IP:9000

After the upgrade of the firmware I made a reset of the wallbox, configured again first the Wifi and then the OCPP server and now the connection seems to be stable again.
