### ISSUE TITLE
Charge rate on 3-phase charger

### ISSUE THREAD

**Issue by confucius78** [lbbrhzn/ocpp#1152]
**Describe the bug**
Setting max amp or using the ‘set charge rate’ service do not affect charge rate on 3-phase Alfen charger. The service execution shows as successful, and setting the amperage works visually but do not affect the actual charge rate. No entries in the log

Integration version is 5.2

**Comment by drc38** [comment]
Have a look at #1035, you'll need to enable debug to see what's going on. It'll be an issue with the charger.

**Comment by confucius78** [comment]
Hold on...this was working fine with this specific integration until a few weeks ago. Does this mean there is new functionality in the integration that is not backwards compatible? Doesn't sound like a charger bug to me.

I'll have a detailed look at the other topic, but seems to me this has nothing to do with the charger.

**Comment by drc38** [comment]
The new service hasn't been modified since its release in 5.2 (it did not exist prior), I suggest debugging to see what's going on.

**Comment by confucius78** [comment]
So I have rolled back to 5.1 and it works again. As this issue was introduced with 5.2, I don’t see how this is a charger bug.

The mentioned other issue may still be a valid pointer, but I do not have the time or knowledge to become familiar enough with ocpp to make it work.

Please let me know if this will be addressed in code moving forward, if not I’ll see how I can manually load the integration and retain v5.1. I can support with testing a fix if it helps

**Comment by drc38** [comment]
Here is the compare between the two versions:
https://github.com/lbbrhzn/ocpp/compare/v0.5.1...v0.5.2
Unless you can identify the issue in the code by way of debug logs there's not much anyone else can do to help.
