### ISSUE TITLE
Integration could not load, after update to Homea Assistant Core 2024.5.3

### ISSUE THREAD

**Issue by juzel69** [lbbrhzn/ocpp#1162]
After update to Version 2024.5.3 the integration could not be started. I removed the integration and reinstall it. But now it is not possible to start it.
![OCPP_Error](https://github.com/lbbrhzn/ocpp/assets/38318706/fef51c51-d00c-4228-9604-f4e9066320b4)

Regards Juerg

**Comment by thomas6779** [comment]
Same here.

**Comment by lutfijw** [comment]
It is because of ha.UnitOfFrequency.HERTZ declaration in const.py file. HA seem to removed it so the integration can not look up the value. Suggest to remove this. I did it and it work good.

**Comment by thomas6779** [comment]
> It is because of ha.UnitOfFrequency.HERTZ declaration in const.py file. HA seem to removed it so the integration can not look up the value. Suggest to remove this. I did it and it work good.

thanks. That works fine!

**Comment by JakobEgPedersen** [comment]
> It is because of ha.UnitOfFrequency.HERTZ declaration in const.py file. HA seem to removed it so the integration can not look up the value. Suggest to remove this. I did it and it work good.

Thank you, this solved my issue. It is working again now.
