### ISSUE TITLE
Alfen single help

### ISSUE THREAD

**Issue by epper202** [lbbrhzn/ocpp#1224]
Hi,
Thanks for the repo however I just can't get it to work. Via modbus everything is working fine but I want to try this instead.

I've installed the occp with 0.0.0.0 and port 9000
no https encryption.

via the ace installer I've set:
backoffice manually enter
network profile 1:
wired (ethernet)
OCPP 1.6
ws://homeassistant.local:9000

Restart but nothing happens

Can you help me out a bit?

**Comment by g3r0nim00** [comment]
> Can you try using your ip address of HA?
> 
> <img alt="Schermafbeelding 2024-08-26 005206" width="583" src="https://private-user-images.githubusercontent.com/28707705/361263772-b9985a16-aecb-4bb3-bf8d-1115791ea3f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzQyNDEsIm5iZiI6MTcyNTUzMzk0MSwicGF0aCI6Ii8yODcwNzcwNS8zNjEyNjM3NzItYjk5ODVhMTYtYWVjYi00YmIzLWJmOGQtMTExNTc5MWVhM2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZmVhYjQ1N2VkMTk5NGI4NDY4Yjc3Yjg4MjI1MjgyNDc1MTM5NDUyY2I2MmFhYmJhYmJmZTZkMWE2NWJhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U0AxMISBIPcbEJo-goeyVS69A98noykBG6Dgy4VcnxY">
> This should also be the same here and in OCCP setup HA! <img alt="Schermafbeelding 2024-08-26 005305" width="598" src="https://private-user-images.githubusercontent.com/28707705/361263777-b24c79e3-8e1d-490a-82f9-b710aa41330f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzQyNDEsIm5iZiI6MTcyNTUzMzk0MSwicGF0aCI6Ii8yODcwNzcwNS8zNjEyNjM3NzctYjI0Yzc5ZTMtOGUxZC00OTBhLTgyZjktYjcxMGFhNDEzMzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwNTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYTZhMzUyZjM0MTFlMTY3MzY2MjhmNTg0ZjU2ODdmY2Y3MDM5MGMxNTcwMGQxZmFlMWMwNGEzM2Y1YWRiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kyWtIrdC3_D7njU_m1BPVYgFolk7UwD_FoYyuqaEvHo">

I think what is missing to your screenshots is the following setting:
<img width="852" alt="image" src="https://github.com/user-attachments/assets/9fbf7251-9afb-46b0-b205-b4337394cb7c">
without "Network profile connection attempt" set to 1, my Alfen Eve Pro Single NG910x didn't start OCPP connectivity
