### ISSUE TITLE
Teltonika TeltoCharge supports additional configuration keys

### ISSUE THREAD

**Issue by triumfas** [lbbrhzn/ocpp#1237]
**Is your feature request related to a problem? Please describe.**
Charging station supports solar charging control which should be available through OCPP. It controls charging station based on energy export.

**Describe the solution you'd like**
Implement additional parameters in OCPP integration.

**Additional context**
Information from a release note: https://wiki.teltonika-energy.com/images/9/91/Release_note_FW_1.12.pdf

New configuration parameters in OCPP - Working with Solar charging feature.
From now on, user will be able to control and visualize Solar charging statuses via OCPP. Configuration keys:

- Solar - to Enable/Disable solar charging (0,1)
- SolarCharging - to select mode “regular/solar/eco/eco_plus"

Modes itself are configured over Bluetooth with vendor mobile app. OCPP could allow enabling it and selecting preferred mode.

**Comment by drc38** [comment]
These are charger specific and not part of the OCPP standard. You should be able to use the Configure service and HA automations etc to implement the new features however.
