### ISSUE TITLE
Maximum number of sampled measurands not queried from the charger

### ISSUE THREAD

**Issue by malaakso** [lbbrhzn/ocpp#1279]
**Describe the bug**
Integration does not query the charger for the maximum number of sampled measurands. During configuration it will try all known measurands one by one, and then tries to configure all supported measurands to be sampled at the same time.

**To Reproduce**
1. Connect charger with maximum number of sampled measurands smaller than the number of all supported measurands.
2. Observe the error message in the logs.

**Expected behavior**
Integration should query the MeterValuesSampledDataMaxLength key and truncate the measurand list accordingly.

**Additional context**
Version 0.58.

**Comment by lbbrhzn** [comment]
v0.5.12 supports manual configuration of the measurands.
