### ISSUE TITLE
The Charging Button Status Doesn't Update Based on the Diagnostic

### ISSUE THREAD

**Issue by MugunthKumar** [lbbrhzn/ocpp#1291]
I'm using a Smappee EV Line Charger and got OCPP enabled from them.
However, with this integration, the Charge Control switch is not in sync with the charger status as seen below.

**Expected behavior**
The charge control switch should be off when the connector status is suspected

**Screenshots**
<img width="709" alt="Screenshot 2024-08-29 at 12 00 01 AM" src="https://github.com/user-attachments/assets/ec39f096-724d-4ef1-b5b0-895c408387f4">

**Comment by malaakso** [comment]
From central system perspective charging session is still ongoing, even though energy flow is (temporarily) suspended.
