### ISSUE TITLE
Version 0.5.11 does not work at all

### ISSUE THREAD

**Issue by dreimer1986** [lbbrhzn/ocpp#1320]
**Describe the bug**
Installing 0.5.11 causes the OCPP integration to be called not existing. 0.5.10 works fine.

**To Reproduce**
Just update and see

**Expected behavior**

To work as good as 0.5.10 ^^

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version no idea

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 15
 - Browser Chrome
 - Version no idea.

**Additional context**

**Comment by pvprodk** [comment]
Same

![image](https://github.com/user-attachments/assets/ec973a3b-bd56-4ec0-8b1c-c2bbc0b26201)

**Comment by lbbrhzn** [comment]
Sorry, i messed up in creating the release tag. Please try v0.5.12

**Comment by lbbrhzn** [comment]
solved in v0.5.12
