### ISSUE TITLE
Vestel EVC04 - Reconnect every 25s

### ISSUE THREAD

**Issue by pvillmann** [lbbrhzn/ocpp#1323]
**Describe the bug**
Hi, i have connected my Vestel EVC04 mit Firmware v3.166.0 (newest) via OCPP to the custom Integration in HA.
Vestel configuration and Config of Integration is completly default.

My Problem is, the connection drops every 25s and all entity are set to "not available". After additional 25s the connection is established again. (Reconnect counter increase every time by 1)

**To Reproduce**
Install OCPP integration in default way
Active OCPP on Vestel WebUI and set server to ws://ha-ip:9000/
Save

The Homeassistant Logs in debug mode shows:

<img width="1649" alt="image" src="https://github.com/user-attachments/assets/ccf35ad6-d047-41a4-b699-80c3f82709be">

in Vestel Log i the only:
`13.09.2024-11:32:41 [INFO] CLIENT: Client RX: [4,"7cfd7ec2-6340-4994-b797-bf5f9851b5d2","InternalError","An unexpected error occurred.",{}]13.09.2024-11:32:41 [INFO] response waiting :1...`

Notifications from HomeAssistant:

<img width="381" alt="image" src="https://github.com/user-attachments/assets/a8301d26-33bf-411c-adae-3798c8763fdd">

**Comment by pieewiee** [comment]
looks like it is a problem with your Python pip package 

https://pypi.org/project/python-chargepoint/

based on the reuqirments.txt you need ocpp==1.0.0

**Comment by drc38** [comment]
The error comes from the underlying ocpp package. You can raise the issue here https://github.com/mobilityhouse/ocpp

**Comment by pvillmann** [comment]
Done 

https://github.com/mobilityhouse/ocpp/issues/661

**Comment by stefa168** [comment]
Hi, I have the same issue with a SCAME Parre Wallbox.

**Comment by pvillmann** [comment]
https://github.com/mobilityhouse/ocpp/issues/661#issuecomment-2370362820

Can someone support here what's the best way to get python debug log in homeassistant for ocpp package?
I'm no HA developer :(

**Comment by pvillmann** [comment]
As described in mobilityhouse/ocpp#661 is not a ocpp package problem.

You need to add some checks before calling float(value)
This is server side, so in "lbbrhzn/ocpp".
