### ISSUE TITLE
2 Vestel ECV04 in HA, cannot add second one + strange information come to HA

### ISSUE THREAD

**Issue by schr3cke** [lbbrhzn/ocpp#1340]
Hi,

I've added one wallbox to my HA via OCCP integration. I think it works, not tested with a car yet. Issues is, I do have two wallboxes of the same type and I cannot add the second one - or - I dont know how to do that.

Furthermore stranges thinks are happening:
"Wallbox_left" is integrated, IP: .19, SN:123
When loging into Wallbox_right (IP: .20, SN:456) Browser Admin Portal and soft rebooting it, HA pushes messages like "Wallbox_left rebotet". 

OCPP Wallbox config is
ws://homeassistant.local:9000
ID: Wallbox_left, Wallbox_right
IPs are fix

Could you help please?

**Comment by lbbrhzn** [comment]
just add another ocpp device, with a different port number.
