### ISSUE TITLE
Unexpected state class in HA core-2021.9.x 

### ISSUE THREAD

**Issue by Rep-Hueman** [lbbrhzn/ocpp#138]
## Version of the custom_component
"version": "0.3.7"

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Unexpected state class
The following entities do not have the expected state class 'total_increasing'
sensor.charger_energy_active_import_register (measurement)

```text
sensor.py

change (state_class: measurement) to  (state_class: total_increasing)
remove -->   self._last_reset = homeassistant.util.dt.utc_from_timestamp(0)


```

**Comment by lbbrhzn** [comment]
yep, this is a change in HA 2021.9.x
