### ISSUE TITLE
"The unit of measurement of some entities has changed" warning messages

### ISSUE THREAD

**Issue by lechercheur123** [lbbrhzn/ocpp#1403]
Hello

**Describe the bug**
Everytime I restart Home Assistant, I have 2 messages saying the unit of measurement of 2 entities have changed:
![Capture](https://github.com/user-attachments/assets/5370dc36-1d79-4662-bd9a-60a1474be747)
(Sorry it is in French. It is saying "The unit of sensor.charger2_power_reactive_import has changed" and "The unit of sensor.charger2_energy_reactive_export_register has changed"

If I click on one message, I get this:
![Capture1](https://github.com/user-attachments/assets/694fc838-d0b0-43f1-98d4-babb557028f7)
In English it means:

> The unit has changed
> The unit of "charger2 Power Reactive Import" (sensor.charger2_power_reactive_import) has been changed to "kW" which cannot be converted to the previously stored unit, "var".
> If the historical statistics values ​​have the wrong unit, you can update the units of the old values. The values ​​will not be updated.
> Alternatively, you can choose to delete all historical statistics values ​​and start over.
> How do you want to fix this issue:
> Option 1: Update the unit of historical statistics values from "var" to "kW", without conversion
> Option 2: Delete old data

The same warning can be found in the logs:
```
2024-11-24 16:05:10.127 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.charger2_energy_reactive_import_register is changing, got multiple {'kWh', 'varh'}, generation of long term statistics will be suppressed unless the unit is stable and matches the unit of already compiled statistics (varh). Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-11-24 16:05:10.207 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.charger2_energy_reactive_export_register (kWh) cannot be converted to the unit of previously compiled statistics (varh). Generation of long term statistics will be suppressed unless the unit changes back to varh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-11-24 16:05:10.207 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.charger2_power_reactive_import (kW) cannot be converted to the unit of previously compiled statistics (var). Generation of long term statistics will be suppressed unless the unit changes back to var or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
```

It is not a blocking issue, but it is annoying to have to open these messages everytime I have to reboot HA (after an update, after a configuration change...)

**To Reproduce**
1. Restart HA

**Expected behavior**
Nothing

**Screenshots**
See above

**Desktop:**
 - OS: Windows (HA is on a VM on a Proxmox hypervisor)
 - Browser Firefox
 - Version 132

**Additional context**
I think this issue might be linked to the charger. In fact, I have two chargers connected to my HA:
- charger, an Schneider EVlink Smart Wallbox 22kW, which is working fine with the OCPP integration. Its ID is "charger22kW"
- charger2, a eProWallbox Move from free2move, which I think is a crappy wallbox. Its ID is 1694AB070000244

I only have the issue with "charger2" (as seen on the screenshots)

To have 2 chargers on the same HA I used two instances of the OCPP integration listening to different ports, like this:
![Capture2](https://github.com/user-attachments/assets/13af42b7-2d93-4894-9ca2-3cc91f1e134b)

I guess this is the good way to do, no?

I will put the log file in attachment.
[home-assistant_ocpp_2024-11-24T16-52-05.376Z.log](https://github.com/user-attachments/files/17894264/home-assistant_ocpp_2024-11-24T16-52-05.376Z.log)

**Comment by onlyfornetwork** [comment]
I have the same problem,
 
it also occurs when the column is turned on by the  integration 

Wallbox Legrand Green Up 059006

**Comment by N3rdix** [comment]
The repair should disappear if you delete the old long-term statistics (if you don't need them from those entities).
I assume there was a reason to change the UOM of those entities, so this might be the only persistent option...

**Comment by lechercheur123** [comment]
If I delete the warning saying that the unit has been changed from 'var' to 'kW', at the next reboot I have a warning saying the unit has been changed from 'kW' to 'var'...
So this isn't a long term fix

**Comment by drc38** [comment]
You can try updating the logic here: 
https://github.com/lbbrhzn/ocpp/blob/a55913cec503110b6b2a5270bcd5f57e145ac19a/custom_components/ocpp/sensor.py#L152
with `SensorDeviceClass.REACTIVE_ENERGY`

**Comment by N3rdix** [comment]
I created a PR to fix at least the power reactive sensors, maybe you can review if it'S fine from your perspective @drc38.
There is no equivalent for reactive energy in the device classes of HA as it seems...

**Comment by drc38** [comment]
> I created a PR to fix at least the power reactive sensors, maybe you can review if it'S fine from your perspective @drc38. There is no equivalent for reactive energy in the device classes of HA as it seems...

Yeah, looks like I was looking at a fork that did not get merged by the devs. See my suggestion on energy in your PR. It should stop the warning by not giving it a device class.
