### ISSUE TITLE
Sensors come and go

### ISSUE THREAD

**Issue by smbunn** [lbbrhzn/ocpp#141]
## Version of the custom_component

v0.3.7   (with the input_number code)
-->

## Configuration

No yaml requried

## Describe the bug

When first installed and launched OCPP gets most of the parameters from my Evnex unit.  I see them under 'configuration..Device''"  and in the panel copied to Lovelace.  Then gradually most of them disappear.   The log file linked below shows this occuring, you can see parameters like serial number and firmware version lilsted at 17:36:10 but by 17:40:24 the same query (getConfiguration) returns significantly less parameters

## Debug log

https://pastebin.ubuntu.com/p/jtnXCr3Nnm/

**Comment by lbbrhzn** [comment]
solved in v0.3.8

**Comment by lbbrhzn** [comment]
Can you check if this issue is solved in v0.3.8?  We have corrected an issue with ping timeouts.

**Comment by smbunn** [comment]
Yes, this seems to be all fixed now in v0.3.9.  Thanks for the very fast releases!  Much appreciated

**Comment by lbbrhzn** [comment]
great!
