### ISSUE TITLE
sensor.charger_temperature has unknown unit Celsius

### ISSUE THREAD

**Issue by Rep-Hueman** [lbbrhzn/ocpp#180]
## Version of the custom_component
0.3.14

## Configuration

```yaml

```

## Describe the bug

**sensor.charger_temperature has unknown unit Celsius**

It really should be  °C 

## Debug log

```text

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:264
Integration: Sensor (documentation, issues)
First occurred: 01:05:10 (1 occurrences)
Last logged: 01:05:10

sensor.charger_temperature has unknown unit Celsius

```

**Comment by lbbrhzn** [comment]
we need a mapping function to translate occp units to ha units
