### ISSUE TITLE
Second OCPP

### ISSUE THREAD

**Issue by tane64** [lbbrhzn/ocpp#188]
OCPP is already in use in my Wallbox. 
Is there a option to connect the Wallbox to HA via OCCP?

**Comment by dreimer1986** [comment]
That can only your Wallbox manufacturer answer to you. This addin creates a OCPP where a Wallbox connects to when you hand it the IP. If a Wallbox can connect to two of them is likely not the case though.

**Comment by lbbrhzn** [comment]
I don't think there is anything we can do in the integration that influences this, so i'll close the issue.
