### ISSUE TITLE
NRGKICK 2 (KfW)

### ISSUE THREAD

**Issue by thecem** [lbbrhzn/ocpp#212]
## Version of the custom_component
v0.3.21

## Configuration
Configured like in the repo description:

charge point Identity: NRGKICK

![EA5BB810-ECA9-4A3E-A13C-67DF09A41D7C](https://user-images.githubusercontent.com/46648579/143749307-e519ba3c-25d2-4e73-a6d4-daa6b3815603.jpeg)

```yaml
charge point Identity: NRGKICK
```

## Describe the bug

The NRGKICK could not connected. Is the config right? What do you need to analyze or add NRGKICK to this repo?

Thanks a lot!

## Debug log

```text

Add your logs here.

2021-11-28 10:16:50 INFO (MainThread) [custom_components.ocpp] {'host': '0.0.0.0', 'port': 9000, 'csid': 'central', 'cpid': 'NRGKICK', 'meter_interval': 60, 'monitored_variables': 'Energy.Active.Import.Register,Energy.Reactive.Import.Register,Energy.Active.Import.Interval,Energy.Reactive.Import.Interval,Power.Active.Import,Power.Reactive.Import,Power.Offered,Power.Factor,Current.Import,Current.Offered,Voltage,Frequency,RPM,SoC,Temperature,Current.Export,Energy.Active.Export.Register,Energy.Reactive.Export.Register,Energy.Active.Export.Interval,Energy.Reactive.Export.Interval,Power.Active.Export,Power.Reactive.Export'}
```

**Comment by lbbrhzn** [comment]
It appears your charger did not contact the OCPP central server. 

- You may need to reset you charger before it switches to the new OCPP server.
- Is the charger on the same network as your home assistant server?

**Comment by thecem** [comment]
Same network, access to ocpp server in HAis possible.
I tried to sniff the packets from the NRGKICK no response.
I captured some traffic between the app and the NRGKICK via Charles, seems to be ws:// too.
But was never able to get a try (packet) from NRGKICK to the OCPP Server.
Seems to be that there is some issue with the firmware, I try to get some information from the vendor Dinitech.at.

Actually installed:

![957323A9-2F8E-43D3-AEA0-08295DADD220](https://user-images.githubusercontent.com/46648579/143770691-2fbe8b68-e9fc-4285-8005-a0a49532e57f.jpeg)

**Comment by thecem** [comment]
captured some packets:
[nrg21.zip](https://github.com/lbbrhzn/ocpp/files/7617763/nrg21.zip)

**Comment by dreimer1986** [comment]
Just a idea on my side. As I NEED the last / on my wallbox, did you try ws://192.168.176.100:9000/ ?

**Comment by thecem** [comment]
I tried, but even with / no result. Thanks a lot..

**Comment by lbbrhzn** [comment]
did you try withouth ws:// ?

**Comment by bardahlm** [comment]
The packet dump show traffic from HA to the web port (port 80) on the charging station, there is no OCPP traffic in the capture.

```
1	0.000000	192.168.76.100	192.168.76.151	TCP	74	36938 → 80 [SYN] Seq=0 Win=64240 Len=0 MSS=1460 SACK_PERM=1 TSval=126991611 TSecr=0 WS=128
2	0.024789	192.168.76.151	192.168.76.100	TCP	60	80 → 36938 [RST, ACK] Seq=1 Ack=1 Win=28694 Len=0
```

**Comment by thecem** [comment]
In between there is some fw update:

![B39B35E4-AA15-471B-8539-DADE70BDAF5F](https://user-images.githubusercontent.com/46648579/150540531-9f91c19d-3f83-4914-8d26-42551d348eed.jpeg)

**Comment by lbbrhzn** [comment]
This seems to be a charger issue, not related to the integration. Closing...

**Comment by KETRF** [comment]
Hi,

I wanted to share an alternative software that might be more suitable for this application and is compatible with the current software version of the NRGkick. You can check out the OCPP.Core project, which is an OCPP (Open ChargePoint Protocol) server written in .NET 8. It includes a management Web-UI for administration of charge points and charge tokens (RFID-Token).

You can find more information and the software at the following link: [OCPP.Core GitHub Repository]
(https://github.com/dallmann-consulting/OCPP.Core?tab=readme-ov-file#status).

Best regards,
