### ISSUE TITLE
Compatible with Grizzl-E Smart EVSE

### ISSUE THREAD

**Issue by malaiwah** [lbbrhzn/ocpp#224]
I did test my Grizzl-E Smart charger against my Home Assistant installation.
https://grizzl-e.com/grizzl-e-smart/

The EVSE Firmware is currently 5.43.

Once the OCPP integration was installed via HACS, I did a wifi-reset on the EVSE, got into the UC_something wifi SSID and opened up a browser to 192.168.4.1 (default static IP of the EVSE) and I entered in `<local_ip>:9000` for the portal configuration URL (instead of their acharger.ca)

All seems to be well with it, it could be added to the list of compatible/tested-with devices.

![image](https://user-images.githubusercontent.com/10375593/145595237-76d5f819-70eb-4262-9b9b-964596b3643d.png)
![image](https://user-images.githubusercontent.com/10375593/145595277-f3a68cd8-b979-47e4-89d6-c366b8dbde73.png)
![image](https://user-images.githubusercontent.com/10375593/145595332-cd8180ec-3594-4705-9f8b-21b12ff2d53a.png)
![image](https://user-images.githubusercontent.com/10375593/145595396-5042d354-2480-49d5-8f3d-039c9ef380d3.png)
![image](https://user-images.githubusercontent.com/10375593/145595442-2451021a-3b87-48e4-8e22-795bee2cda60.png)

**Comment by dreimer1986** [comment]
Hmm, I wonder what are the differences between yours and this EVSE: https://github.com/lbbrhzn/ocpp/issues/176

**Comment by tube0013** [comment]
I just tried mine again, I thought it had not been connected for a while to any server, it's now showing firmware 05.51 if you 05.43 - which I think mine was at originally. any chance you can unplug the charger and hook into the esp32 and read the FW off it with esptool?

**Comment by lbbrhzn** [comment]
no action needed. closing.

**Comment by wipeout666** [comment]
@tube0013 I can do that for you, I still have FW 05.43. I have esptool ready, just have no idea what is the flash size. If you can find out, I'll do a flash_read for you. And the baudrate, if that matters (I've never done such a flash dump for a ESP32)

**Comment by wipeout666** [comment]
United Charge just told me that v5.6 is adding back the ability to provide your own OCPP URL.

**Comment by lbbrhzn** [comment]
See #442 for results with a recent firmware version.
