### ISSUE TITLE
Add CTEK Chargestorm Connected 2 to list of supported devices

### ISSUE THREAD

**Issue by jonasbkarlsson** [lbbrhzn/ocpp#287]
I have been using this OCPP integration with the device CTEK Chargestorm Connected 2 (FW ccu_R3.11.18.1) for a while now.
[https://www.ctek.com/uk/ev-charging/chargestorm%C2%AE-connected-2](https://www.ctek.com/uk/ev-charging/chargestorm%C2%AE-connected-2)

I works really well, so if you like, please add it to the list of supported devices.

**Comment by lbbrhzn** [comment]
will, thanks!

**Comment by lbbrhzn** [comment]
done
