### ISSUE TITLE
Titles for the measurand selection are not showing?

### ISSUE THREAD

**Issue by drc38** [lbbrhzn/ocpp#30]
@lbbrhzn, any ideas on why I'm not seeing the labels when adding the new integration?
![image](https://user-images.githubusercontent.com/20024196/123526468-4456bc80-d72c-11eb-96dd-fdd8acdd6e15.png)

**Comment by lbbrhzn** [comment]
Hmm, strange. I renamed the translation file to i-default.json, which should be loaded when there is no language specific translation.

**Comment by lbbrhzn** [comment]
i've tried to reproduce the issue, but failed. I added nl.json, this is user language is set to 'Nederlands'. Selecting a language that does not have a .json file will default to i-default.json.

**Comment by drc38** [comment]
A minimum HA version may need to be added. I was running a Docker version dated 2021/04/19, once I updated it to 2021.6.6 then it worked perfectly!

**Comment by lbbrhzn** [comment]
Ok, I guess this can be done in the manifest.json?
