### ISSUE TITLE
Services are not registered anymore?

### ISSUE THREAD

**Issue by dreimer1986** [lbbrhzn/ocpp#389]
**Describe the bug**
The services are not registered to Home Assistant anymore? Wanted to try the firmware update with the official ftp from Everon I sniffed the data to. The list is missing the services though.

**To Reproduce**
Go to the dev tools and look for your services, no OCPP ones there...

**Expected behavior**
There were services, and I would like to ask to bring them back

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 100.0

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] MS Surface Duo
 - OS: [e.g. iOS8.1] Android 11
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] 100.0

**Additional context**

**Comment by drc38** [comment]
@dreimer1986, the services haven't gone anywhere 😉. So suggest remove integration and start over with a fresh setup.

**Comment by drc38** [comment]
Ocpp services are not registered until your charger has connected properly, so check the log to ensure the charger has connected properly.

**Comment by dreimer1986** [comment]
![image](https://user-images.githubusercontent.com/29841368/153506523-51337f0f-3e1c-4ff0-9a1d-27541b5e679d.png)
Well, properly enough that it gets the current status. Still the list does not give me any OCPP entry. This thing (HA or the addin, or both?) really hates me. ^^ New funny idea to mess with my charger in form or a firmware update and some karma finds a new crazy way forcing me to stop.

**Comment by drc38** [comment]
hmmm... can only suggest there is some issue with your HA setup as nothing I'm aware of has changed in the codebase on the services side.

**Comment by drc38** [comment]
Looking at a compare between those versions not much has changed, nothing directly relating to the services. I had an issue with Websockets reverting to version 9.1 rather than 10.1 on HA. Worth checking, it can be forced with `pip websockets --upgrade` if on 9.1

**Comment by dreimer1986** [comment]
That's not so easy on HassOS. But an interesting problem... will investigate here, too

**Comment by drc38** [comment]
@lbbrhzn  added the following in `post_connect`, which my charger does not support, so another avenue to check:
```
if prof.REM in self._attr_supported_features:
                if self.received_boot_notification is False:
                    await self.trigger_boot_notification()
```

**Comment by GrantKeymer** [comment]
> That's not so easy on HassOS. But an interesting problem... will investigate here, too

Yes it can be done, but I admit it's not easy.  I am also running HassOS but I managed to make it happen.  You need to convince Docker to give you access to the Bash shell.  If you don't know how to do that, I'll post some more details.

**Comment by dreimer1986** [comment]
As I can not sleep now anyways... First I finished my "regress" testing:

0.4.11: Services registered
0.4.12: No services registered

@GrantKeymer I am always interested in such tricks :D

**Comment by GrantKeymer** [comment]
> @GrantKeymer I am always interested in such tricks :D

Here you go...

Start Terminal mode
Enter `docker -ps`
Note the PIDs for each entry, the one you need is `homeassistant`
Enter `docker exec -it <PID> /bin /bash` without the angle brackets

Now you should be in the Bash shell.  Do the PIP websockets upgrade as posted above.

**Comment by drc38** [comment]
> await self.trigger_boot_notification()

In that case it looks like it could be `await self.trigger_boot_notification()`, try commenting it out and see how you get on.

**Comment by dreimer1986** [comment]
> In that case it looks like it could be `await self.trigger_boot_notification()`, try commenting it out and see how you get on.

And it is. At least this makes 0.4.12 work fine. Six services registered. When I remove the "#" again and reboot, they are gone again.
Sadly there seems to be some more changes up to head in that part, to reverting just that one line in head is not doable.

**Comment by dreimer1986** [comment]
Lil update. Commenting out these two:
```
                if self.received_boot_notification is False:
                    await self.trigger_boot_notification()
```
helps up to 0.4.16. Later does still not show the services. Rest of the analyze will follow later

**Comment by drc38** [comment]
> Lil update. Commenting out these two:
> 
> ```
>                 if self.received_boot_notification is False:
>                     await self.trigger_boot_notification()
> ```
> 
> helps up to 0.4.16. Later does still not show the services. Rest of the analyze will follow later. I don't think I will find the reason in the later versions though...

You'll need to provide the HA log showing why it's not working, is the boot trigger message timing out or something else?

**Comment by dreimer1986** [comment]
Any special additions to logging or as always the typical ones for addon debug? Not that some home assistant ones would be interesting here, too.

**Comment by dreimer1986** [comment]
I just made a log for you, hopefully a useful one. It starts with the reboot after reinstalling 0.4.20 and ends with Box connected to addon and all sensors are active + a while for safety.
[home-assistant.log](https://github.com/lbbrhzn/ocpp/files/8053300/home-assistant.log)

My logger settings for that:
```
logger:
  default: info
  logs:
    pyfritzhome: critical
    ocpp: debug
    custom_components.ocpp: debug
    websockets: debug
    asyncio: debug
```

**Comment by drc38** [comment]
Hmm... log looks pretty normal. Your charger responds to the trigger notifications ok. Only odd aspect is the connection closing. If that always happens before `post_connect` finishes it could cause an issue.

**Comment by dreimer1986** [comment]
Changed api.py accordingly... nothing changed over here.
[home-assistant.log](https://github.com/lbbrhzn/ocpp/files/8054298/home-assistant.log)

**Comment by dreimer1986** [comment]
Ignoring causes a 6 MB log quite fast as it rus in a endless loop for a while then. Right now not at home, so I can't sent a log. But services are not there. Log will follow later

**Comment by drc38** [comment]
I've moved the trigger statements to after the services load in #392

**Comment by dreimer1986** [comment]
OK, did try again and now the services are back alive :D I copied over your "drc38-patch-22" completely for that.

Don't know if some of the new log is interesting for you, but here it is.
[home-assistant.log](https://github.com/lbbrhzn/ocpp/files/8054869/home-assistant.log)

Thanks for the fix :D

**Comment by lbbrhzn** [comment]
I suspect the trigger boot notification triggers a real reboot (which is not conform spec, that's what reset is for) resulting in a reconnect. After a reconnect, post_connect is skipped.

To work around this, we can either:

1. Make sure post_connect survives a close and reconnect.
2. trigger the boot notification in the end (drc38 patch) of post_connect (if not received).
3. call post_connect after reconnect (if not finished), skipping the trigger of already done.

Option 1 was our initial approach. It was a dirty hack, that resulted in additional processes being spawned for each reconnect, causing a lot of grief. So let's leave that behind.

Option 2 and 3 could both work.
I like option 3 a bit better, because a reboot could reset some or all of the configuration we're doing in post_connect. We can combine these approaches though, by moving the trigger to the end anyway.

Note that when a spontaneous boot notification is received (untriggered, could be due to a firmware update) we should redo post_connect (but skip the boot notification trigger).

**Comment by drc38** [comment]
#392 does a combination of options 2 and 3

**Comment by drc38** [comment]
I don't think redoing post_connect after a spontaneous boot is strictly necessary, as ocpp settings should be retained across a firmware update. If we don't it keeps things a lot simpler too :)

**Comment by dreimer1986** [comment]
At least I can confirm that the settings you can easily see are all left intact after the firmware update was done. Network, power source, ocpp server, unlock card config, all still there.
