### ISSUE TITLE
Missing metrics on Wallbox Pulsar Plus?

### ISSUE THREAD

**Issue by Strixx76** [lbbrhzn/ocpp#454]
## Version of the custom_component
0.4.26

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

In the documentation `Voltage` and `Frequency` is listed as "_Useful Entities for Wallbox Pulsar Plus_". I have a Pulsar Plus with current firmware version 5.5.10 but I do not get any values for those metrics.
Something wrong with my charger, firmware or is the documentation not correct?

## Debug log

```text

Add your logs here.

```

**Comment by GrantKeymer** [comment]
I wrote the User Guide with the list of `Useful Entities`.  I'm still using v0.4.21 of this integration, but I don't know whether that makes any difference compared to the version you're using.  Please note that Voltage and Frequency only update during a charging session, not when the charger is idle.

**Comment by Strixx76** [comment]
While reading through some posts in the Discussions I have noticed that we have different models even though they are all named Pulsar Plus.
My model number is: PLP1-M-2-4

And I can not get any readings when charging.

**Comment by GrantKeymer** [comment]
Good point!  I have PLP1-0-2-2.  It will be interesting to see which version @lbbrhzn is using.

**Comment by GrantKeymer** [comment]
![Pulsar Plus Models](https://user-images.githubusercontent.com/35156198/159884824-b021eb06-30e4-409b-a01b-8dea02b9a8d0.png)

It seems you have a Type 2 version with 7m cable and 3-phase 22kW capability.

**Comment by GrantKeymer** [comment]
Here's a further thought, given that you have a 3-phase version.  Did you try looking in the Extra Attributes of the Voltage Sensor?

![Voltage - Extra Attributes](https://user-images.githubusercontent.com/35156198/159885937-07699576-ba9d-4257-81be-7663371299aa.png)

**Comment by Strixx76** [comment]
I do have the 3-phase, 22kW, type 2 box with 7m cable.
The sensor value is `unknown`, and has no attributes.

**Comment by lbbrhzn** [comment]
I'm running FW version 5.5.10 on my PLP1-0-2-4

**Comment by lbbrhzn** [comment]
@GrantKeymer, Is it possible you have the additional readings because of the external power meter you installed?

**Comment by Strixx76** [comment]
I also have the external power meter (Power Boost, Carlo Gavazzi EM340) using Modbus to communicating with the Pulsar Plus

**Comment by GrantKeymer** [comment]
@lbbrhzn - No, I removed the external energy meter and sent it back many weeks ago.

**Comment by lbbrhzn** [comment]
@Strixx76, I also have that. But I thought @GrantKeymer hade one configured differently, for Eco-Smart charging.

**Comment by lbbrhzn** [comment]
I don't get Frequency or Voltage.

**Comment by Strixx76** [comment]
Could it be that it is the EV that is reporting it to the charger?

**Comment by lbbrhzn** [comment]
Seems unlikely.  I think we can close this issue, it is not related to the integration.

**Comment by Strixx76** [comment]
Sure. Should the documentation be updated?

**Comment by GrantKeymer** [comment]
> Sure. Should the documentation be updated?

Yes, I'll update the User Guide with a note that the Voltage and Frequency metrics don't work on 3-phase versions of the Pulsar Plus.

There are a few improvements I want to make, so this will be one of them.  Thanks guys for checking up on this issue.
