### ISSUE TITLE
Use the ZULU timeformat to support more chargers

### ISSUE THREAD

**Issue by hugoEnovates10** [lbbrhzn/ocpp#512]
The current datetime format used in the ocpp responses is not recommend and may cause problems with some chargepoint manufactures.

`datetime.now(tz=timezone.utc).isoformat()`
should be best be replaced with 
`datetime.now(tz=timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')`

This is the recommended datetimeformat by the OCPP documents and OCA.

[ocpp_home_assistant_zulu.patch.txt](https://github.com/lbbrhzn/ocpp/files/8669724/ocpp_home_assistant_zulu.patch.txt)

**Comment by lbbrhzn** [comment]
closing, since the change has been merged
