### ISSUE TITLE
ID Charger Elli - Volkswagen group compatibility?

### ISSUE THREAD

**Issue by turkano** [lbbrhzn/ocpp#533]
## Version of the custom_component

v0.4.32

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Recientemente Elli ha actualizado los ID Charger para capacitarlos con EEBUS y OCPP 2.0, tras actualizarlo, al intentar conectar con OCPP se muestran los siguientes errores, alguna idea de lo que puede estar ocurriendo o lo que puedo estar haciendo mal?

<img width="667" alt="Captura de Pantalla 2022-06-01 a las 20 43 37" src="https://user-images.githubusercontent.com/90693784/171479080-cfcb0ecf-d13f-46e1-ad55-2faceed7a5f9.png">

Si no Marco Secure Connection el registro de errores es distinto: 

Logger: homeassistant.config_entries
Source: custom_components/ocpp/api.py:182 
Integration: Open Charge Point Protocol (OCPP) ([documentation](https://github.com/lbbrhzn/ocpp/blob/main/README.md), [issues](https://github.com/lbbrhzn/ocpp/issues)) 
First occurred: 18:12:58 (2 occurrences) 
Last logged: 20:45:19

Error setting up entry central for ocpp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ocpp/__init__.py", line 71, in async_setup_entry
    central_sys = await CentralSystem.create(hass, entry)
  File "/config/custom_components/ocpp/api.py", line 182, in create
    server = await websockets.server.serve(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 1088, in __await_impl__
    server = await self._create_server()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1506, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('192.168.1.55', 9000): address not available

## Debug log
 Marcando Secure Connection
Logger: homeassistant.config_entries
Source: custom_components/ocpp/api.py:173 
Integration: Open Charge Point Protocol (OCPP) ([documentation](https://github.com/lbbrhzn/ocpp/blob/main/README.md), [issues](https://github.com/lbbrhzn/ocpp/issues)) 
First occurred: 19:16:20 (1 occurrences) 
Last logged: 19:16:20

Error setting up entry central for ocpp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ocpp/__init__.py", line 71, in async_setup_entry
    central_sys = await CentralSystem.create(hass, entry)
  File "/config/custom_components/ocpp/api.py", line 180, in create
    self = CentralSystem(hass, entry)
  File "/config/custom_components/ocpp/api.py", line 173, in __init__
    self.ssl_context.load_cert_chain(localhost_pem)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by drc38** [comment]
See https://github.com/lbbrhzn/ocpp/pull/506 for instructions noting the secure option has not been tested and may not work.

**Comment by are0002** [comment]
> Error setting up entry central for ocpp Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/ocpp/**init**.py", line 71, in async_setup_entry central_sys = await CentralSystem.create(hass, entry) File "/config/custom_components/ocpp/api.py", line 182, in create server = await websockets.server.serve( File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 1088, in **await_impl** server = await self._create_server() File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1506, in create_server raise OSError(err.errno, 'error while attempting ' OSError: [Errno 99] error while attempting to bind on address ('192.168.1.55', 9000): address not available

La configuración se refiere al servidor ocpp que se va a levantar en tu home assistant. Es decir que debes poner o la IP del home assistant o bien 0.0.0.0 para especificar cualquier IP que tenga tu dispositivo. Por eso se queja que esa IP no existe en tu home assistant.
