### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by lbbrhzn** [lbbrhzn/ocpp#56]
We should improve automated testing.
There are some automated tests defined that I took from an example project, but these currently fail.

Some somple tests we should add:
- test configFlows and optionFlow 

A more complicated test:
- add a Charge Point simulator, verify that our CentralSystem / ChargePoint implementation can connect with it

**Comment by drc38** [comment]
Some progress made towards fixing automated tests in #62

**Comment by drc38** [comment]
Further progress in #72 on charge point simulator

**Comment by lbbrhzn** [comment]
Solved
