### ISSUE TITLE
Not able to stop/start VESTEL

### ISSUE THREAD

**Issue by Ilupo4399** [lbbrhzn/ocpp#742]
First - Thanks much for this integration !

HA v02023.1.4 running on docker 
Using latest ocpp integration
Charger - Vestel EVC04
Firmware v1.65.0-1.0.85.0
I connect to the charger and on ocpp Im getting many entities ,
I'm trying to contorol charger operation using 
switches: charger control - nothign happened .
Same for charger unlock .
For charger Availability button - it always show off.

I'd simply like to have an option to start/stop charging .
![image](https://user-images.githubusercontent.com/99248884/212678728-f87fcc80-3e24-4cf6-a0c9-a29ceee8a818.png)

**Comment by drc38** [comment]
Turning `Charge Control` off will stop your charger if it supports it, you'll need to look at the debug log messages to see what's going on and may need to raise it with your charger manufacturer.
