### ISSUE TITLE
Split Features list into separate items

### ISSUE THREAD

**Issue by lbbrhzn** [lbbrhzn/ocpp#78]
**Is your feature request related to a problem? Please describe.**
The charger.Features sensor shows the list of supported features as a list of comma separated strings. This does not display nicely on small screens (phone) and is cumbersome to access in scripts. 

**Describe the solution you'd like**
It would be better to create separate (binary) sensor metrics for each possible feature.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/8673442/125983161-85450c10-189b-45a5-b628-29e72b235e93.png)

**Comment by drc38** [comment]
You might be able to follow this example to set them up as flags https://community.home-assistant.io/t/sensors-with-flags-in-automation/311415

**Comment by lbbrhzn** [comment]
I think the example uses state attributes. That would require a custom sensor that adds these attributes. That would work, but what would be the main sensor value to show, perhaps Status?

**Comment by drc38** [comment]
Main sensor value could be `Core` which all chargers must support?

**Comment by lbbrhzn** [comment]
Ok, I'll try when I get back from my holiday. There's a limit to what you can do from your mobile phone! 😎
