### ISSUE TITLE
no unique ID generated for this  sensor.

### ISSUE THREAD

**Issue by jeremycoppey** [lbbrhzn/ocpp#8]
To manipulate this integration in HASS it would be nice that it generates a unique ID
https://www.home-assistant.io/faq/unique_id/
For the moment it looks like this: 
![image](https://user-images.githubusercontent.com/13691266/121883814-7cb0d080-cd12-11eb-8895-f1f60dead956.png)

**Comment by lbbrhzn** [comment]
A concatenation of chargePointVendor,chargePointModel,changePointSerialNumber should be sufficient to uniquely identify the charge point. These are reported by a BootNotification.conf message. A sensor should could add some unique ID, for instance the Measurand name. Do you think this would work?

**Comment by jeremycoppey** [comment]
Solved by @drc38 when you guys merged his pull request #7 . 
Use "name" property in yaml config
closing this.
