### ISSUE TITLE
Add to HACS default integrations

### ISSUE THREAD

**Issue by lbbrhzn** [lbbrhzn/ocpp#80]
## Version of the custom_component
v0.3.0

## Configuration

Not applicable

## Describe the bug

Ocpp currently needs to be added as an additional repository to hacs. By adding ocpp to the HACS default integration list, this step is no longer needed

## Debug log

Not applicable.

**Comment by lbbrhzn** [comment]
I've opened a [pull request](https://github.com/hacs/default/pull/1027) on hacs/default. If we pass all checks, and the PR is approved, we can remove the addition of the repository from our installation instructions.

**Comment by lbbrhzn** [comment]
Note that restart of home assistant should not be needed after adding the integration, since we use a configflow for our setup. See [here](https://hacs.xyz/docs/categories/integrations/)

**Comment by lbbrhzn** [comment]
pull request for adding to HACS has finally been accepted!

**Comment by drc38** [comment]
Worth bumping the release?

**Comment by lbbrhzn** [comment]
well, it does not need any code changes... but I did update the readme.

**Comment by drc38** [comment]
HACS defaults to 0.3.4 (rather than main) so now 25+ days old

**Comment by lbbrhzn** [comment]
done
