### ISSUE TITLE
Charge Control not working with EVLink Wallbox

### ISSUE THREAD

**Issue by stibbzy** [lbbrhzn/ocpp#918]
I have an issue whereby my EVLink Wallbox is rejecting Charge Control turn on requests after a turn off request has been issued. I can successfully issue a turn off request using the UI toggle switch, and the charger will stop charging. However, if I then toggle the switch on, it switches off again and I get this error in the log:

2023-09-26 09:18:58.585 INFO (MainThread) [ocpp] b41725: send [2,"0cf4db24-978b-4d1b-9e01-82988679b1ab","GetConfiguration",{"key":["AuthorizeRemoteTxRequests"]}]
2023-09-26 09:18:58.794 INFO (MainThread) [ocpp] b41725: receive message [3,"0cf4db24-978b-4d1b-9e01-82988679b1ab",{"configurationKey":[{"key":"AuthorizeRemoteTxRequests","readonly":true,"value":"false"}]}]
2023-09-26 09:18:58.796 INFO (MainThread) [ocpp] b41725: send [2,"5e2f5bbb-c7ef-4327-80d3-15b126847da9","RemoteStartTransaction",{"idTag":"b41725","connectorId":1}]
2023-09-26 09:18:58.821 INFO (MainThread) [ocpp] b41725: receive message [3,"5e2f5bbb-c7ef-4327-80d3-15b126847da9",{"status":"Rejected"}]
2023-09-26 09:18:58.821 WARNING (MainThread) [custom_components.ocpp] Failed with response: Rejected

The light on the charging station will also turn red. However, if I unplug the cable, the light turns green. I can then toggle the charge control on, and it works as expected, until another stop request is issued followed by a start request.

I've configured the charger to allow remote start etc, but given I can start it remotely after unplugging it, authentication doesn't seem to be the issue. 

The 'Status Connector' state after I use the toggle to stop the charge stays at 'Finishing' indefinitely. It seems because of that, I can't initiate a new charging session. Unplugging it removes the 'Finishing' status, so a new session can start.

This is the charger log:

Mon Sep 25 23:18:57 2023 Received RemoteStartTransaction _connectorId=1 _idTag=b41725
Mon Sep 25 23:18:57 2023 Sent RemoteStartTransactionConf: Rejected
Mon Sep 25 23:19:21 2023 Received ChangeAvailability connectorId=0 type=Operative
Mon Sep 25 23:19:21 2023 Sent ChangeAvailabilityConf: Accepted
Mon Sep 25 23:19:25 2023 Sent GetConfigurationConf configurationKeys: 1
Mon Sep 25 23:19:25 2023 Received RemoteStartTransaction _connectorId=1 _idTag=b41725
Mon Sep 25 23:19:25 2023 Sent RemoteStartTransactionConf: Rejected
Mon Sep 25 23:20:21 2023 Received ChangeAvailability connectorId=0 type=Operative
Mon Sep 25 23:20:21 2023 Sent ChangeAvailabilityConf: Rejected
Mon Sep 25 23:21:01 2023 Sending StatusNotificationReq: connectorld=1 Available
Mon Sep 25 23:21:01 2023 Received StatusNotificationConf
Mon Sep 25 23:21:20 2023 Sending StatusNotificationReq: connectorld=1 Preparing
Mon Sep 25 23:21:20 2023 Received StatusNotificationConf
Mon Sep 25 23:21:28 2023 Sent GetConfigurationConf configurationKeys: 1
Mon Sep 25 23:21:28 2023 Received RemoteStartTransaction _connectorId=1 _idTag=b41725
Mon Sep 25 23:21:28 2023 Sent RemoteStartTransactionConf: Accepted Mon Sep 25 23:21:31 2023 Sending StartTransactionReq tag:b41725
Mon Sep 25 23:21:31 2023 Received StartTransactionConf transactionId: 1695684092 status: Accepted
Mon Sep 25 23:21:33 2023 Sending StatusNotificationReq: connectorld=1 Charging
Mon Sep 25 23:21:33 2023 Received StatusNotificationConf

Version of the custom_component: v0.4.41

## Configuration

# Evse Conf

[FUNCTIONAL]
operatingMode=           1
clusterManagement=       0
simplifiedMode3=         true
ventilation=             false
localisation=            false
stateFDelayPwmOff=       0
stateFDelayPwmOn=        3
evChargeTimeout=         30
cpwRateStep=             0
isolatedInput1=          0
isolatedInput2=          0
diStatusExpected=        0x0002
diStatusEnable=          0x2602
autoTestEnable=          0x7FFFFFFF
SM3CurrentLowThreshold=  1
SM3MaxCurrent=           10
SM3StopDelay=            3600
postponeCharge=          false
allowPluggedCable=       true
enableEvDetection=       false
schukoWithNoDetectionEndOfCharge=       60
updateSetPointPeriodInSec=       15
remoteSetPointPeriodInSec=       5
stationNetworkType=       3
dhcp=                     1
strictDhcpMode=           0
slaveHasPublicIp=         1
stationName=              N 20265 20 007 003
ssdp=                     1
dhcpMode=                 1
loadSheddingSetPoint=0

[ENERGY]
voltageRerefence=        400
currentPB1=              32
nbPhase=                 1
maxIntensitySocket=      32
ocppSmartChargingSetPoint=      32
maxIntensityStation=      64
maxTEValue=      14

HeadMeterType=5
HeadMeterProtocol=1
HeadMeterRTUAddress=1
HeadMeterGatewayAddress=130
HeadMeterPhase=1
StationMeterType=5
StationMeterProtocol=1
StationMeterRTUAddress=2
StationMeterGatewayAddress=130
StationMeterPhase=1
AlternativeMeterType=5
AlternativeMeterProtocol=1
AlternativeMeterRTUAddress=3
AlternativeMeterGatewayAddress=130
AlternativeMeterPhase=3
MeteringPollingPeriod=1000
PowerMeterPhasesConnection=7
TerminalPhasesConnection=7
[HISTORY]
CurrentChargeLogPeriod=60

[HMI_CONTROL]
EnableSuspendChargeByButton=true

[PROXY]
proxyEnabled=             0
proxyHost=                UNDEFINED
proxyPort=                0
proxyAuthentication=      0
proxyUsername=            UNDEFINED
proxyPassword=            2F94F0C34B68214E48D66C08D6893B2B
proxyUseHttps=            0
proxyUseHttpParam=        0

[TIME]
useAutoTimeManagment=     false
timeServerName=           pool.ntp.org
timezone=                 UTC

[EVLINK ENERGY]
pulseToEnergyFactor=1
degradedModeSetPointMono=8
degradedModeSetPointTri=14
monophasedLoadSheddingFloorValue=8
triphasedLoadSheddingFloorValue=14
EMsetting=2
EMRemoteModBusLifeTimeout=10
upstreamProtHighTrshld=100
homeUpstreamProtection=32

[ENERGY SHARING]
staticMaxIntensityCluster=32
loadSheddingPriority=0
loadSheddingPeriod=900
phaseRotation=true

[ALTERNATIVE CHARGE]

[CURRENT MEASUREMENT]       
currentAdjustementSlope=    722
currentAdjustementOffset=   0
lowOvercurrentTolerance=    10
mediumOvercurrentTolerance= 25
highOvercurrentTolerance=   70
lowOvercurrentDelay=        1010
mediumOvercurrentDelay=     5
highOvercurrentDelay=       1
iMaxStation=                32
overloadDelay=              90
overloadTolerance=          18

[AUTHENTICATION]
enableUnknownUser=       true
authenticationManager=   0
rfidStatusTimeout=       10
masterkeyAvailability=   false
authenticationMode=      1
supervisionSystem=       2
ControlChargeByRemoteCommand=true

# Ocpp Conf

[OCPP]
ocppVersion=              1.6
ocppCentralAddress=       ws://192.168.0.40:9000
ocppBoxLocalPort=         8080
ocppBoxPublicIp=          
ocppBoxPublicPort=        8080
ocppBoxLocalSSL=          0
ocppBoxAddressReplyTo=    http://www.w3.org/2005/08/addressing/anonymous
ocppModemIpAddress=       192.168.0.254
ocppModemPresence=       0
modemType=                
confModemRetryInterval=   30
boxIdentity=              b41725
defaultIdTag=             b41725
isMeterValueSimulated=    false
MeterValuesAlignedData=   Energy.Active.Import.Register
MeterValuesSampledData=   Energy.Active.Import.Register,Current.Import,Current.Offered,Voltage
meterValueSampleInterval= 60
clockAlignedDataInterval= 900
ocppConnectTimeOut=       60
WebSocketPingInterval=    60
MinimumStatusDuration=    0
TransactionMessageRetryInterval=60
TransactionMessageAttempts=500
truncateBootNotificationsSerialNumbers=    true
serverCertificatePassword=UNDEFINED
clientHttpsOptions=       DEFAULT
cacheListEnabled=         false
enablePlugNumbering=      false
enableDoubleNotification=      false
lastAcceptedOcppCentralAddress=ws://192.168.0.40:9000/b41725
lastAcceptedBoxIdentity=       b41725
lastAcceptedHeartBeatInterval= 3600
compressDiagnostic=            1
ocppEMDegradedModeEnabled=     0

# Report Conf

[REPORT_GLOBAL]
GlobalLogReportPeriod=0
FieldSeparator=1
DecimalSeparator=1
PublicationProtocol=1
Language=en-gb

[REPORT_CHARGE_LOGS]
SmtpAuthentication=true
SmtpLogin=EVB1A7PCKI3N20265200070035122BB2
SmtpPassword=70C92756644C6B5057683B863E2FEE47CA892E04032653A81A9FEA9899219BAB9C0F035E8F965209146DBC6E4D19B351
SmtpSender=
SmtpServer=
SmtpPort=587
SmtpLogsReceiver=

[REPORT_ALARM]
AlarmEnabled=true
AlarmAuthent=true
AlarmLogin=EVB1A7PCKI3N20265200070035122BB2
AlarmPassword=70C92756644C6B5057683B863E2FEE47CA892E04032653A81A9FEA9899219BAB9C0F035E8F965209146DBC6E4D19B351
AlarmSender=service@wallboxmail.com
AlarmServer=
AlarmPort=587
AlarmReceiver=

[REPORT_FTP]
FtpAuthent=false
FtpLogin=
FtpPassword=2F94F0C34B68214E48D66C08D6893B2B
FtpServer=
FtpPort=21
FtpPassif=0

[REPORT_HTTP]
HttpAuthent=false
HttpLogin=
HttpPassword=2F94F0C34B68214E48D66C08D6893B2B
HttpServer=
HttpPort=80
HttpPath=/
HttpField=

[REPORT_HTTPS]
HttpsAuthent=0
HttpsLogin=
HttpsPassword=2F94F0C34B68214E48D66C08D6893B2B
HttpsServer=
HttpsPort=80
HttpsPath=/
HttpsField=

[SMTP]
authentication=true
login=EVB1A7PCKI3N20265200070035122BB2
password=70C92756644C6B5057683B863E2FEE47CA892E04032653A81A9FEA9899219BAB9C0F035E8F965209146DBC6E4D19B351
sender=
server=
port=25
receiver=""

[WIFI]
port=8000

# Update Conf

[UPDATE_GLOBAL]
GlobalFwUpdateProtocol=0
DefaultPackageName=evse

[UPDATE_HTTP]
HttpLogin=
HttpPassword=2F94F0C34B68214E48D66C08D6893B2B
HttpServerAddr=192.168.0.101
HttpPort=80
HttpPath=

[UPDATE_FTP]
FtpLogin=
FtpPassword=2F94F0C34B68214E48D66C08D6893B2B
FtpServerAddr=
FtpPort=21
FtpPath=

[UPDATE_TFTP]
TftpServerAddr=
TftpPath=

**Comment by drc38** [comment]
I have a different charger but it works in the same way as yours, only option seems to be to manually unplug or reset. Instead I simply set max charge rate to 0 rather than use switch.

**Comment by stibbzy** [comment]
> I have a different charger but it works in the same way as yours, only option seems to be to manually unplug or reset. Instead I simply set max charge rate to 0 rather than use switch.

Yeah I figured out the same after lots of trial and error. The issue with that is that it makes it hard to integrate as a custom charger into evcc.io. Evcc expects to be able to issue a charger enable/disable, and while I can automate a disable command to '0' amps, I can't automate an enable command to a variable charge amps.

**Comment by drc38** [comment]
evcc.io has its own ocpp interface, what happens when you use it directly rather than through HA?

**Comment by stibbzy** [comment]
Unfortunately, it doesn’t appear to conform to OCPP 1.6 perfectly. It has the same issue as home assistant when evcc tries to set the charger to off. This is when it’s set up under an OCPP template in evcc. 
Evcc does have a dedicated EVLink integration, but it requires a sponsor token.
