### ISSUE TITLE
EVbox BusinessLine Hub/Satelite

### ISSUE THREAD

**Issue by PDXPill** [lbbrhzn/ocpp#921]
Hi, i'm testing at moment to use this OCPP integration with homeassistant. We have four EVbox BusinessLine chargers. One of them is the Hub and the others are "satelites". I can only configure the hub to connect to a specific OCPP platform. The integration recognised 4 connectors but i'm not able to control them individualy. Do you have a solution? 
Thanks!

**Comment by dreimer1986** [comment]
There was a pull request regarding multiple connectors: https://github.com/lbbrhzn/ocpp/pull/803 But as it seems the former reporter vanished. Right now this addin does not allow control of multiple connectors.

**Comment by lbbrhzn** [comment]
i've been working on better support for multiple chargers and multiple connectors... work in progress.
