### ISSUE TITLE
UOM issue only with "Energy Active Import Register"

### ISSUE THREAD

**Issue by KKlausl** [lbbrhzn/ocpp#948]
Running OCPP Integration - and it works like charm! thank you very much for this, it literally was the reason to migrate to HA from OH.

there is one small issue, which I (a newbee) think, that the integration could ve responsible of (please correct me if Im wrong!).

Energy Active Import Register shows kWh - but it´s clear, it has to be Wh. It would be no problem to template this, but Im eager to know, if there is a way to cleanly integrate this register without any "tricks".

thank you for any help or fix!

**Comment by drc38** [comment]
Why do you think it has to be Wh?

**Comment by KKlausl** [comment]
thank you for your question, I should have described it better in the first place. 
my wallbox is new and the sensor (which is total_increasing) showed 3 days ago ca. "300.000" and after charging 30kW to my car it showed "330.000"... Im relatively shure it has to be Wh.

**Comment by drc38** [comment]
You show a decimal point which indicates a change of 30kWh. Or should that be a comma? Please include log details and a screenshot of the sensor. If the raw value is in Wh the integration _should_ convert it to kWh.

**Comment by KKlausl** [comment]
my bad - the decimal point was just for better reading. I show you screenshots - but I have no idea where to find "logs" to that sensor - could you guide me to the correct data? 
![beforecharging](https://github.com/lbbrhzn/ocpp/assets/78704429/38e56f45-3999-410d-849c-ee0daedcb523)
![aftercharging](https://github.com/lbbrhzn/ocpp/assets/78704429/fd2934c1-a130-4998-b844-ea67e7ada321)

**Comment by KKlausl** [comment]
Here another one (Wallbox is now available)
![Clipboard01](https://github.com/lbbrhzn/ocpp/assets/78704429/d64e77a7-856f-415f-876f-fa6193b3cfe1)

**Comment by drc38** [comment]
Thanks, I see you've got an ABB unit. @nlindn changes in v0.4.42 (just published) should fix the issue.

**Comment by KKlausl** [comment]
Wow, thank you for your help. :)) After Updating and Rebooting everything still works fine - the historical resp total_increasing value of the sensor is unchanged, but I guess, next charging will be decisive. I will post the outcome here… Thank you!!! :))

**Comment by KKlausl** [comment]
that´s it - after starting a new session, evt works fine! you´ve solved this issue, thank you very much!! :)

![Solution](https://github.com/lbbrhzn/ocpp/assets/78704429/b32ced06-c66c-499e-833c-d7379058e392)
