### ISSUE TITLE
using Enums that inherit from str

### ISSUE THREAD

**Issue by lbbrhzn** [lbbrhzn/ocpp#99]
**Is your feature request related to a problem? Please describe.**
Key values are currently defined in enums, which is great for preventing typos through linting. The syntax that is currently used is a bit verbose though:

```python
self._metrics[om.Frequency.value]=value
```

**Describe the solution you'd like**
With enums derived from str (Using multiple inheritance) you can use the enum value itself as a string value, so you can use:

```python
self._metrics[om.Frequency]=value
```

**Describe alternatives you've considered**
None

**Additional context**
See [here](https://stackoverflow.com/questions/58608361/string-based-enum-in-python#58608362) for more info.

**Comment by drc38** [comment]
Agree, we should raise this in upstream repo for consistency.

**Comment by lbbrhzn** [comment]
mobilityhouse/ocpp is already doing this.

**Comment by drc38** [comment]
The approach used in mobilityhouse/ocpp provides a string but not of the value assigned. Eg  Measurand.voltage returns the string "Measurand.voltage". Instead the class could be defined as a `StrEnum` as per this

**Comment by lbbrhzn** [comment]
in mobilityhouse/occp repo the enums are used to translate from pythonic snake case enum keys to OCPP camel case strings. Since these strings are part of the OCPP standard, these values should not be changed. I don't feel we should propose upstream to change their approach.

**Comment by lbbrhzn** [comment]
closed, nothing to be done.
